### ISSUE TITLE
Pre-installation: manually added dependencies

### ISSUE THREAD

**Issue by agustinf** [platanus/admin-invitable#2]
I must say I am not completely sure of what I'm about to say, but I think having gems as part of a manual pre-installation is probably not correct. If our gem needs other gems to work, then those gems should be part of the gem's dependencies, am I right?

**Comment by ldlsegovia** [comment]
@agustinf I'm not sure about this. The [devise invitable README](https://github.com/scambra/devise_invitable#installation) says: "Add DeviseInvitable to your Gemfile (and Devise if you weren't using them)". I thought that was not necessary to add the gems as dependencies. But, inspecting the [code](https://github.com/scambra/devise_invitable/blob/master/devise_invitable.gemspec#L26) I find devise on gemspec. So, I will put dependencies on gemspec. @juliogarciag what do you think about this?

**Comment by juliogarciag** [comment]
@ldlsegovia I really don't know why they want us to add Devise explicitly. ActiveAdmin does that too, but i don't know if that's correct. Maybe they did in that way because Devise is a main dependency that requires an installation process and some configuration to work correctly, and in this way they ensure that the developer using the gem knows he is using devise under the hood. Adding `devise_invitable` as a dependency in the gemspec doesn't seem to show the same kind of problems, so i'd add it as a dependency.
